_format_version: "2.1"
_transform: true

services:
  - name: real-time-service
    url: http://host.docker.internal:6002/
    routes:
      - name: real-time-routes
        paths:
          - /real-time
  - name: account-service
    url: http://host.docker.internal:6001/
    routes:
      - name: account-routes
        paths:
          - /account